### ISSUE TITLE
intrinsicpr: crash when running tests with gc64

### ISSUE THREAD

**Issue by CapsAdmin** [fsfod/LuaJIT#6]
```
(gdb) run runtests.lua 
Starting program: /home/caps/goluwa/framework/lua/build/luajit_forks/repo/fsfod-intrinsicpr_debug-assert_52compat_gc64/src/luajit runtests.lua
running fpr
running gpr
running gpr64

Program received signal SIGSEGV, Segmentation fault.
0x000000001815fe74 in ?? ()
(gdb) bt
#0  0x000000001815fe74 in ?? ()
#1  0x00000000004594e4 in lj_intrinsic_call (cts=0x7fbb7afe4c48, ct=0x7fbb7afdfa08) at lj_intrinsic.c:916
#2  0x00000000004b49e6 in lj_ccall_func (L=0x7fbb7b003378, cd=0x7fbb7afc0fb0) at lj_ccall.c:1156
#3  0x000000000043cc4a in lj_cf_ffi_meta___call (L=0x7fbb7b003378) at lib_ffi.c:232
#4  0x0000000000444de2 in lj_BC_FUNCC ()
#5  0x000000000041c28c in lua_pcall (L=0x7fbb7b003378, nargs=0, nresults=-1, errfunc=2) at lj_api.c:1129
#6  0x00000000004046ae in docall (L=0x7fbb7b003378, narg=0, clear=0) at luajit.c:121
#7  0x000000000040504d in handle_script (L=0x7fbb7b003378, argx=0x7fffffffd840) at luajit.c:291
#8  0x0000000000405d61 in pmain (L=0x7fbb7b003378) at luajit.c:551
#9  0x0000000000444de2 in lj_BC_FUNCC ()
#10 0x000000000041c57a in lua_cpcall (L=0x7fbb7b003378, func=0x405b81 <pmain>, ud=0x0) at lj_api.c:1153
#11 0x0000000000405e71 in main (argc=2, argv=0x7fffffffd838) at luajit.c:580
```

**Comment by fsfod** [comment]
It crashing in the wrapper generated for the intrinsic i think. I remember rebasing on a branch with gc64 before fixing tons of merge conflicts but maybe I missed adding support for 64 bit sized gc object pointers to the wrappers.
